name: Docker
on:
  - push
env:
  DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}
  ALIYUN_DOCKER_USERNAME: ${{secrets.ALIYUN_DOCKER_USERNAME}}
  ALIYUN_DOCKER_TOKEN: ${{secrets.ALIYUN_DOCKER_TOKEN}}
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Build
        run: |
          chmod +x build.sh
          ./build.sh test1
          ./build.sh test2
